[bundles]

[plugins]
modelix-model-api-gen = { id = "org.modelix.model-api-gen", version.ref = "modelixCore" }
npm-publish = { id = "dev.petuska.npm.publish", version = "3.5.2" }

[versions]
modelixCore = "11.2.1"
kotlinCoroutines="1.10.1"
ktor="3.0.3"

[libraries]
modelix-model-api = { group = "org.modelix", name = "model-api", version.ref = "modelixCore" }
modelix-model-api-gen-runtime = { group = "org.modelix", name = "model-api-gen-runtime", version.ref = "modelixCore" }
modelix-authorization = { group = "org.modelix", name = "authorization", version.ref = "modelixCore" }
modelix-model-client = { group = "org.modelix", name = "model-client", version.ref = "modelixCore" }
modelix-model-server = { group = "org.modelix", name = "model-server", version.ref = "modelixCore" }
modelix-modelql-core = { group = "org.modelix", name = "modelql-core", version.ref = "modelixCore" }
modelix-modelql-untyped = { group = "org.modelix", name = "modelql-untyped", version.ref = "modelixCore" }
modelix-modelql-html = { group = "org.modelix", name = "modelql-html", version.ref = "modelixCore" }
modelix-model-datastructure = { group = "org.modelix", name = "model-datastructure", version.ref = "modelixCore" }
modelix-mps-model-adapters = { group = "org.modelix.mps", name = "model-adapters", version.ref = "modelixCore" }
modelix-mpsApi = { group = "org.modelix.mps", name = "stable-api", version = "1.1.1" }

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.5" }
kotlin-logging-microutils = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }
kotlin-html = "org.jetbrains.kotlinx:kotlinx-html:0.12.0"
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinCoroutines" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }

zt-zip = { group = "org.zeroturnaround", name = "zt-zip", version = "1.17" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.16" }
jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version = "2.18.2" }
